dist: trusty

language:
    - php
php:
    - 5.6.4

addons:
  browserstack:
    username: vaishali52
    access_key:
        secure: XEIwRb/Qx/E/hbYNKTwiEg8RR7t6jCRueUA/7o9q563YqRNc7u0MwPqRULgQczbgNmLRMFZUvDA2IzVefL7kv1mlKXiIXvZcMN0qa5+teaNltLiQeTCUy1ZpgGL8TrTPsSI0JA9QaAiHwtzqNH5yqtg85zmG8p1mg/cQ+mPrwLbf1lW7f9Pcj+C366dnOgoZYrDwBKPki8YHtpGV62m+Jgj2UaglIt2MF+Qsa3Da2i5fh3YUAvPF7p3CU7eclxhNto2Luh4SJMVsDY1sBGVqf58eHzJ/TTrv1zwz6Qz1+ikgsyzKPOUpEuuuh096CG3Lg3eDUKAxKb2do9NjsV1Tqzr7hkhMg2WVut5hNVbY110A3+D9UbNCMNyBlSTJXKBfWQem1crMCRl7Jao39Xw+8AjTRkSm3UhPyv4wIVEPB28h2b8H5J1k006dWmNSteRWqjNpLvuQ7eRVSQTESsIgTElrNGUmFqXpsOxG6GJguV8NErOEP0uAOguoLWJOZbfeH6ow3B+XBnDDNP/5iAniPPAfXGLHZLfe4xe9ES6OovpkLNEdiZY8WGH/R8JSmO9yqBFOj3UFQSGt2HH2yK0BJQ7nnLbSff8ZBua2dp/wOC+b8zF1Ay8Zu7d/t/G27Krk5eidesG/LDD4Whc9zV86NSETI9qROBtaoZdEivmjAUs=

before_install:
- rm -rf ~/.gnupg

cache:
  paths:
  - vendor/

before_script:
- export PLUGIN_DIR=$(pwd)
- sudo rm -rf /etc/mysql/
- sudo apt-get -qq purge mysql* graphviz* && sudo apt-get -qq autoremove
- sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
- wget -qO ee rt.cx/ee && sudo bash ee
- sudo ee site create wp.test.me --wp --user=ADMINUSER --email=krupa.nanda@rtcamp.com --pass=ADMINPASS
- sudo sed -i '/^127.0.0.1/ s/$/ wp.test.me/' /etc/hosts
- sudo chmod 777 -R /var/www
- cd /var/www/wp.test.me/htdocs/wp-content/plugins/ && mkdir rtMedia
- cd $PLUGIN_DIR
- cp -Rf * /var/www/wp.test.me/htdocs/wp-content/plugins/rtMedia/
- cd /var/www/wp.test.me/htdocs/
- wp --allow-root plugin install https://downloads.wordpress.org/plugin/buddypress.2.8.2.zip
- wp plugin activate --all
- cd $PLUGIN_DIR
- cd /tmp
# - wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
# - unzip BrowserStackLocal-linux-x64.zip
# - echo $BROWSERSTACK_ACCESS_KEY
# - sudo apt-get install unzip && unzip BrowserStackLocal-linux-x64.zip
- nohup ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY &
- cd $PLUGIN_DIR
- composer install
- export PATH="$PATH:/home/travis/build/kjnanda/Automation-demo/vendor/bin"

script:
- wpcept run acceptance
